name: CI Workflow

# trigger
on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml

  test:
    name: Test the Application
    needs: [build]
    uses: ./.github/workflows/test.yaml

