name: CI Workflow

# trigger
on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.2"

  test:
    name: "Test"
    needs: [build]
    uses: ./.github/workflows/test.yaml
    with: 
      version: "8.2"

  scan:
    name: "CI Code Scan"
    needs: [test]
    uses: ./.github/workflows/sonar-scan.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}